name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.7
    - name: Cross build
      run: make cross
    - name: Create Release
      id: create_release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
    - name: Upload
      run: make upload
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Set variables
      id: variables
      run: |
        git_tag_name="${GITHUB_REF#refs/tags/v}"
        echo "::set-output name=release_tag_patch::${git_tag_name}"
        echo "::set-output name=release_tag_minor::${git_tag_name%.*}"
    - name: Release Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: itchyny/gojq
        tags: latest, ${{ steps.variables.outputs.release_tag_patch }}, ${{ steps.variables.outputs.release_tag_minor }}
